name: my-template

on: [push]

jobs:
    my-job-1:
        runs-on: ubuntu-latest
        steps:
            - name: step-1
              run: echo "Hello world! $my-var"
              env:
                my-var: test
            - name: step-2
              run: echo "Goodbye!"